security:
    role_hierarchy:
        ROLE_ADMIN: [ROLE_WRITER, ROLE_READER]
        ROLE_WRITER: [ROLE_READER]

    providers:
        entity_provider:
            entity: { class: App\Entity\User, property: username }

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: lazy
            guard:
                authenticators:
                    - App\Security\Authenticator\GithubAuthenticator
            logout:
                path: app_logout
